import express from "express";
import bodyParser from "body-parser";

const app = express();
const port = 3000;

app.use(express.static("public"));

app.use(bodyParser.urlencoded({extended: true}));

app.get("/", (req, res) => {
    res.render("index.ejs");
})

app.post("/submit", (req, res) => {
    const randomAdj = adj[Math.floor(Math.random()* adj.length)];
    const randomNoun = noun[Math.floor(Math.random()* noun.length)];
    res.render("index.ejs", {adjective: randomAdj, noun: randomNoun});
})

app.listen(port, () => {
    console.log(`Server started on Port ${port}`);
})

const adj = [
        "Wo wurde Jesus geboren?",
        "Welche Stadt ist der Geburtsort von Jesus?",
        "Wer war der Vater von Maria?",
        "Wer erschien Maria, um ihr die Geburt von Jesus anzukündigen?",
        "Wie hieß die Mutter von Jesus?",
        "Wie hieß der Ehemann von Maria?",
        "Was führte die Weisen nach Bethlehem?",
        "Was machten die Hirten, als sie von der Geburt Jesu erfuhren?",
        "Was ist eine Krippe?",
        "Welche Geschenke brachten die Weisen nach Bethlehem?",
        "Wer sang die Lieder in der Nacht, als Jesus geboren wurde?",
        "An welchem Tag wird Weihnachten gefeiert?",
        "Welche Geschichte erzählen die Evangelien über die Geburt Jesu?",
        "Wie hieß der Engel, der Maria die Geburt von Jesus ankündigte?",
        "Was bedeutet der Begriff 'Erscheinung' in Bezug auf Weihnachten?",
        "Welches Weihnachtslied ist in vielen Kirchen beliebt?",
        "Was war das Wunder der Geburt von Jesus?",
        "Was bedeutet der Glaube für Christen an Weihnachten?",
        "Was bringt Weihnachten in Bezug auf Frieden?",
        "Warum ist Hoffnung ein zentrales Thema in der Weihnachtsgeschichte?",
        "Warum ist Liebe ein wichtiges Thema bei Weihnachten?",
        "Was ist das größte Geschenk, das an Weihnachten gegeben wird?",
        "Wer ist Gottes Sohn in der Weihnachtsgeschichte?",
        "Warum wird Jesus als das Licht der Welt bezeichnet?",
        "Wer ist der König, der in der Weihnachtsgeschichte erwähnt wird?",
        "Welche Bedeutung haben die drei Weisen aus dem Morgenland?",
        "Welche Geschenke brachten die Weisen nach Bethlehem?",
        "Was ist Weihrauch und warum wurde er Jesus geschenkt?",
        "Was ist Myrrhe und welche Bedeutung hat sie in der Weihnachtsgeschichte?",
        "Was bedeutet das Wort 'Schatz' in der Weihnachtsgeschichte?",
        "Was symbolisiert die Friedenstaube in der Weihnachtsgeschichte?",
        "Was bedeutet es, dass Jesus das 'Licht der Welt' ist?",
        "Wer ist der Erlöser in der Weihnachtsgeschichte?",
        "Was bedeutet der Begriff 'Christus' in Bezug auf die Geburt Jesu?",
        "Was ist der Messias und warum ist er für Christen wichtig?",
        "Was sind die Heiligen Schriften im Christentum?",
        "Wer sind die Apostel in der Weihnachtsgeschichte?",
        "Was bedeutet 'Halleluja' und warum wird es oft in Weihnachtsliedern gesungen?",
        "Warum ist das Gebet in der Weihnachtsgeschichte so wichtig?",
        "Was bedeutet Heiligkeit in Bezug auf Weihnachten?",
        "Was ist Gottes Segen, der an Weihnachten gegeben wird?",
        "Wer sind die Jünger Jesu und was haben sie mit Weihnachten zu tun?",
        "Was ist ein Engelsgesang und wie wird er mit der Geburt Jesu verbunden?",
        "Was bedeutet Zukunft im Kontext der Weihnachtsgeschichte?",
        "Was bedeutet Erlösung für Christen an Weihnachten?",
        "Was ist die Bedeutung der Geburt Christi in der Weihnachtsgeschichte?",
        "Wer ist der Heilige Geist in der Weihnachtsgeschichte?",
        "Was ist eine Prophetie und wie betrifft sie Weihnachten?",
        "Was bedeutet das Kreuz für Christen, besonders an Weihnachten?",
        "Was ist der Segen, den Christen an Weihnachten empfangen?",
        "Was ist der Geist Gottes in der Weihnachtsgeschichte?",
        "Was bedeutet Errettung im Zusammenhang mit Weihnachten?",
        "Warum ist die Familie Jesu eine jüdische Familie?",
        "Was ist das Passahfest und welche Verbindung hat es zur Weihnachtsgeschichte?",
        "Was ist Sünde und wie wird sie durch Jesus besiegt?",
        "Was bedeutet das Erlösergeschenk, das mit der Geburt Jesu verbunden ist?",
        "Was ist Versöhnung in der Weihnachtsgeschichte?",
        "Was bedeutet Heil in Bezug auf die Geburt Jesu?",
        "Was ist ein Glaubensbekenntnis im Zusammenhang mit Weihnachten?",
        "Warum ist König David ein wichtiger Teil der Weihnachtsgeschichte?",
        "Was ist Gottes Plan für die Welt, wie es in der Weihnachtsgeschichte dargestellt wird?",
        "Was ist göttliche Hilfe und wie wurde sie in der Weihnachtsgeschichte gegeben?",
        "Was bedeutet Huldigung in Bezug auf die Geburt von Jesus?",
        "Was ist Barmherzigkeit und wie zeigt sie sich an Weihnachten?",
        "Was bedeutet Vergebung und wie ist sie mit der Geburt Jesu verbunden?",
        "Was ist das Geschenk des Lebens, das an Weihnachten gefeiert wird?",
        "Was bedeutet Erfüllung in Bezug auf die Prophezeiung der Geburt Jesu?",
        "Was ist Glaubensstärke und wie kann sie an Weihnachten erfahren werden?",
        "Was ist Trost, der durch die Geburt Jesu gebracht wird?",
        "Was symbolisiert der Stern von Bethlehem?",
        "Was bedeutet es, an den Retter zu glauben, besonders an Weihnachten?",
        "Was ist die Frohe Botschaft, die an Weihnachten verbreitet wird?",
        "Was bedeutet eine christliche Familie an Weihnachten?",
        "Was bedeutet der Name Jahwe in der Weihnachtsgeschichte?",
        "Was ist das Licht des Herrn in der Weihnachtsgeschichte?",
        "Was ist das Wunder der Geburt Jesu?",
        "Was bedeutet Freude in der Weihnachtsgeschichte?",
        "Was ist die Kraft Gottes in der Weihnachtsgeschichte?",
        "Was ist die Bedeutung der Sühne an Weihnachten?",
        "Warum ist Hoffnung ein zentrales Thema in der Weihnachtsgeschichte?",
        "Was ist die Bedeutung der Heiligen Schrift in Bezug auf Weihnachten?",
        "Was bedeutet es, Kraft im Gebet zu finden, besonders an Weihnachten?",
        "Was ist die Bedeutung der Erwartung in Bezug auf die Geburt Jesu?",
        "Was bedeutet es, an die Geburt Jesu zu glauben?",
        "Was ist der Sternenschein, der die Weisen nach Bethlehem führte?",
        "Was bedeutet Vollendung im Zusammenhang mit der Weihnachtsgeschichte?",
        "Was ist Gottes Liebe und wie zeigt sie sich an Weihnachten?",
        "Was ist die biblische Botschaft von Weihnachten?",
        "Was bedeutet Dankbarkeit in der Weihnachtsgeschichte?",
        "Warum ist Weihnachten ein Heiliges Fest?",
        "Was ist göttliche Weisheit und wie wird sie durch Jesus gezeigt?",
        "Warum wird Weihnachten als Fest der Liebe bezeichnet?",
        "Was sind Segenswünsche, die zu Weihnachten geteilt werden?",
        "Was ist eine Glaubensgemeinschaft und wie wird sie an Weihnachten gefeiert?",
        "Wer ist das Heilige Kind in der Weihnachtsgeschichte?",
        "Was ist ein Bibelvers und wie wird er an Weihnachten verwendet?",
        "Was bedeutet göttliche Ruhe in der Weihnachtsgeschichte?",
        "Warum gibt es eine Sehnsucht nach Frieden in der Weihnachtsgeschichte?",
        "Was ist der Tempel von Jerusalem und welche Bedeutung hat er für Weihnachten?",
        "Was ist die Verheißung, die mit der Geburt von Jesus erfüllt wird?",
        "Was bedeutet Gottes Licht in der Dunkelheit an Weihnachten?",
        "Was ist die Huldigung der Weisen und was symbolisiert sie?",
        "Was ist das Reich Gottes und wie wird es in der Weihnachtsgeschichte dargestellt?",
        "Was ist das Gebet des Herrn und warum ist es an Weihnachten wichtig?",
            "Wo wurde Jesus geboren?",
            "Wer war die Mutter von Jesus?",
                "Wo wurde Jesus geboren?",
                "Wie hieß die Mutter von Jesus?",
                "Wer war der Vater von Jesus?",
                "Welches Tier führte Maria nach Bethlehem?",
                "Was brachte der Stern über Bethlehem?",
                "Welche Geschenke brachten die Weisen aus dem Morgenland?",
                "Wie viele Weisen kamen zu Jesus?",
                "Was war der Name des Engels, der Maria erschien?",
                "Wer sah den Engel zuerst, der von der Geburt Jesu sprach?",
                "Welche Tiere waren bei der Geburt von Jesus?",
                "Was war der Name des Königs, der versuchte, Jesus zu töten?",
                "Wo flüchteten Maria und Joseph, um Jesus zu schützen?",
                "Was sagte der Engel zu den Hirten?",
                "Was sangen die Engel, als sie den Hirten erschienen?",
                "Welches Land gehörte zu dem Ort, an dem Jesus geboren wurde?",
                "Was war der Name des Tempels, in dem Jesus nach seiner Geburt gesegnet wurde?",
                "Wie hieß der Prophet, der vor der Geburt Jesu prophezeite?",
                "Was war das Zeichen, das die Hirten zur Krippe führte?",
                "Wer war der erste Mensch, der Jesus als den Messias erkannte?",
                "Was war das erste Geschenk, das den neugeborenen Jesus erreichte?",
                "Wie hieß der Engel, der Joseph in einem Traum erschien?",
                "Was bedeutet das Wort 'Emmanuel'?",
                "Was ist das Symbol für die Geburt Jesu?",
                "Was wurde in der Krippe gelegt, in der Jesus lag?",
                "Warum war das Volk Israel nach einem Retter sehnsüchtig?",
                "Wie viele Tage war die Familie in Bethlehem, bevor sie nach Ägypten floh?",
                "Warum reisten Maria und Joseph nach Bethlehem?",
                "Was gab der Engel den Hirten zu tun, nachdem sie den Engel gesehen hatten?",
                "Was ist der Grund, warum wir Weihnachten feiern?",
                "Welche Prophezeiung erfüllte sich mit der Geburt Jesu?",
                "Wer war der Herrscher von Rom zur Zeit der Geburt von Jesus?",
                "Wie heißt der Kalender, der die Geburt Jesu markiert?",
                "Was war der Beruf von Joseph, dem Vater von Jesus?",
                "Wie hieß der erste Mensch, der Jesus in den Armen hielt?",
                "Was bedeuteten die Geschenke Gold, Weihrauch und Myrrhe?",
                "Wer sprach die Worte 'Ehre sei Gott in der Höhe'?",
                "Was ist das wichtigste Ereignis, das an Weihnachten gefeiert wird?",
                "Welche Bibelstelle beschreibt die Geburt Jesu?",
                "Was war das Ziel der Reise von Maria und Joseph?",
                "Welche Rolle spielten die Engel in der Weihnachtsgeschichte?",
                "Warum mussten Maria und Joseph in einer Krippe übernachten?",
                "Wer waren die ersten Zeugen der Geburt Jesu?",
                "Was bedeutete der Stern von Bethlehem?",
                "Wie wurde Jesus von den Weisen geehrt?",
                "Was bedeutet 'Weihrauch' im Zusammenhang mit der Geburt Jesu?",
                "Warum wurden die Weisen nach einem neuen König gesucht?",
                "Wie reisten die Weisen nach Bethlehem?",
                "Welche Stadt wurde mit der Geburt Jesu in Verbindung gebracht?",
                "Was ist das wahre Geschenk, das an Weihnachten gefeiert wird?",
                "Wer sind die 'Heiligen Drei Könige' in der Weihnachtsgeschichte?",
                "Warum gab es keine Unterkunft für Maria und Joseph?",
                "Was zeigt uns die Weihnachtsgeschichte über die Liebe Gottes?",
                "Was bedeutet es, wenn Jesus als 'Licht der Welt' bezeichnet wird?",
                "Wie wird der Name 'Jesus' in der Bibel erklärt?",
                "Warum wird Weihnachten als Fest der Liebe bezeichnet?",
                "Was bedeutet die Zahl 'Drei' in Bezug auf die Weisen?",
                "Welche Geschenke wurden dem neugeborenen Jesus von den Weisen gebracht?",
                "Was ist das wichtigste Symbol von Weihnachten?",
                "Was ist die Bedeutung von 'Gott mit uns'?",
                "Was passiert in der Geschichte der Geburt von Jesus?",
                "Was bedeutet es, dass Jesus als 'Erlöser' bezeichnet wird?",
                "Welche Rolle spielte die Jungfrau Maria in der Geburt von Jesus?",
                "Was bedeutet 'Frieden auf Erden'?",
                "Warum wurde der Engel als Nachrichtenträger von Gott gewählt?",
                "Welche Bedeutung hat das Lied 'Stille Nacht'?",
                "Wie hieß die Stadt, in die Maria und Joseph für die Volkszählung reisten?",
                "Was sagte der Engel zu den Hirten in der Nacht der Geburt?",
                "Was ist der wichtigste Vers aus der Weihnachtsgeschichte?",
                "Wie lange war die Reise von Maria und Joseph nach Bethlehem?",
                "Was symbolisiert das Weihnachtsfest für Christen?",
                "Warum mussten Maria und Joseph nach Bethlehem reisen?",
                "Welche Bedeutung hat die Geburt Jesu für Christen?",
                "Warum reisten die Weisen aus dem Morgenland?",
                "Wie nennt man die Zeit vor Weihnachten in der christlichen Tradition?",
                "Was wurde in den Evangelien über die Geburt Jesu gesagt?",
                "Wer erkannte Jesus als den Messias, als er in den Tempel gebracht wurde?",
                "Warum war die Geburt Jesu ein Ereignis der Freude?",
                "Wie viele Engel erschienen den Hirten in der Nacht von Jesu Geburt?",
                "Welche Bedeutung hat das 'Licht' im Weihnachtskontext?",
                "Warum wird Jesus in der Weihnachtsgeschichte als Retter bezeichnet?",
                "Was bedeutete die Reise der Weisen nach Bethlehem?",
                "Warum gab es so viele Engel in der Geschichte der Geburt Jesu?",
                "Was ist die Rolle der Hirten in der Weihnachtsgeschichte?",
                "Wie wird die Krippe in der Weihnachtsgeschichte dargestellt?",
                "Warum feiert die Kirche Weihnachten?",
                "Was bedeutet das Wort 'Messias'?",
                "Was ist das Bild des Sterns von Bethlehem?",
                "Was ist das Wichtigste an der Weihnachtsgeschichte?",
                "Wie wird Jesus als der 'König der Könige' bezeichnet?",
                "Was steht in der Weihnachtsgeschichte über das 'Licht'?",
                "Warum ist die Krippe so ein starkes Symbol in der Weihnachtsgeschichte?",
                "Warum feiern Christen Weihnachten?",
                "Welche Rolle spielte die Stadt Bethlehem in der Geschichte von Jesus?",
                "Wie wird der Name 'Emmanuel' in der Weihnachtsgeschichte verwendet?",
                "Was ist die Bedeutung von 'Frohe Weihnachten' in der christlichen Tradition?",
                "Was war die Reaktion der Hirten auf die Ankündigung der Geburt Jesu?",
                "Welche biblischen Texte sprechen von der Geburt von Jesus?",
                "Warum ist die Weihnachtsgeschichte ein zentraler Bestandteil des christlichen Glaubens?",
                "Was bedeutet es, dass Jesus als 'Licht' und 'Retter' beschrieben wird?",
                "Was ist das zentrale Thema der Weihnachtsgeschichte?",
                "Warum wird Weihnachten als Fest der Hoffnung und des Friedens gefeiert?"
                
];

const noun = [
    " Helene", 
    " Andreas"," Erika"," Linda"," Jim Ellis"," Tim Andi"," John Lewin"," Tom Leonell"," Mariella",
    " Johann"," Vali"," Luis"," Evelyn"," Ben",
    " Wowa"," Anna"," Ruth-Kind"," Laura"," Esther"," Marco"," Lucas"," Jasmin",
    " Elvira",
    " Maria"," Sophia"," Yasmin",
    " Paul",
    " Moni",
    " Boris"," Bettina"," Emely"," Kati"," Peter"," Sarah"," Lena-Maria",
    " Martin"," Kseniia",
    " Ruth-groß"," Viktor"," Hanna Ruth"," David"," Paul"
];

